# Generated by Django 3.1.7 on 2021-03-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210303_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_category',
            options={'verbose_name_plural': 'main_categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'sub_categories'},
        ),
    ]
